select * from [TBL_PERSON]


alter table TBL_PERSON
ADD CONSTRAINT ABCD
DEFAULT 3 FOR [GENDER ID]
INSERT INTO TBL_PERSON (ID,NAME,EMAIL) 
VALUES (10,'JOHNY','J@J.COM')
select * from [TBL_PERSON]

insert into TBL_PERSON VALUES (8,'baba','baba.com',1,47)
--insert into TBL_PERSON VALUES (8,'baba','baba.com',1,-47) ##SHOWS ERROR
INSERT INTO TBL_PERSON VALUES (9,'KAKA','KAKA.COM',1,NULL)

ALTER TABLE TBL_PERSON
ADD CONSTRAINT CK_TBL_PERSON1 CHECK (AGE>0 AND AGE<150)
 
ALTER TABLE TBL_PERSON
DROP CONSTRAINT CK_TBL_PERSON

INSERT INTO TBL_PERSON1 VALUES ('A')
select * from TBL_PERSON1
 
INSERT INTO TBL_PERSON1 VALUES ('B')
INSERT INTO TBL_PERSON1 VALUES ('C')
 --ONLY ONE VALUE IS ADDED AT ONE TIME

DELETE FROM TBL_PERSON1 WHERE PERSONID=1

INSERT INTO TBL_PERSON1 VALUES ('D')
 --TO ASSIGN VALUE 1 AGAIN WE HAVE TO ON THE IDENTITY INSERT

INSERT INTO TBL_PERSON1 VALUES (1,'E')
 -- IT IS THROWING ERROR
--TO OVERCOME THIS 
SET IDENTITY_INSERT TBL_PERSON1 ON
INSERT INTO TBL_PERSON1 VALUES (1,'E')
--AGAIN ERROR

INSERT INTO TBL_PERSON1 (PERSONID,NAME) VALUES (1,'E')
select * from TBL_PERSON1


INSERT INTO TBL_PERSON1 VALUES ('F')
-- ERROR AS WE HAVE TO TURNOFF IDENTITY INSERT

SET IDENTITY_INSERT TBL_PERSON1 OFF
INSERT INTO TBL_PERSON1 VALUES ('F')
 
 DELETE FROM TBL_PERSON1
 INSERT INTO TBL_PERSON1 VALUES ('G')
 -- AGANIN TO ASSIGN FROM VALUE 1 WE NEED
 DBCC CHECKIDENT(TBL_PERSON1, RESEED, 0)

 ------------------------------------------------------------------------------------------------------
 CREATE TABLE PRACITCE8
 (
 ID INT IDENTITY(1,1),
 VALUE NVARCHAR(20)
 )
 
 CREATE TABLE PRACITCE8A
 (
 ID INT IDENTITY(1,1),
 VALUE NVARCHAR(20)
 )

 INSERT INTO [PRACITCE8] VALUES ('X')
 SELECT * FROM [PRACITCE8]
 
 SELECT SCOPE_IDENTITY()
 --IT GIVES THE LAST GENERATED IDENTITY COLUMN VALUE

 INSERT INTO [PRACITCE8] VALUES ('Y')
 SELECT @@IDENTITY
 -- SAME AS SCOPE_IDENTITY
 
 ----UNIQUE KEY CONSTRAINT
ALTER TABLE TBL_PERSON
ADD CONSTRAINT UQ_TBL_PERSON_EMAIL UNIQUE(EMAIL)

SELECT * FROM TBL_PERSON
INSERT INTO TBL_PERSON VALUES (11,'MONU', 'J@COM',2,22)
---IT THROWS ERROR AS EMAIL IS UNIQUE KEY AND ALL VALUES IN IT SHOULD BE UNIQUE FOR EMAIL COLUMN

ALTER TABLE TBL_PERSON
DROP CONSTRAINT UQ_TBL_PERSON_EMAIL
INSERT INTO TBL_PERSON VALUES (11,'MONU', 'J@COM',2,22)
--NOW THIS COMMAND EXECUTES 

SELECT * FROM TABLENAME WHERE NAME LIKE '[MST]%'
--THIS QUERY WILL TAKE ALL THOSE NAMES WHICH START WITH M S OR T
---VE OF THIS IS '[^MST]%'
--SELECT * FROM TABLENAME WHERE NAME LIKE '_@_.COM'  # HERE _ IS FOR ONLY ONE ANY CHARACTER
---SELECT TOP 1 * FROM .............. OREDR BY......... IT WILL GIVE THE TOP RANK OPLY IN OREDR 


----------------------------------------------------------------------------------------------------------------
use test 
go

select * from [authors]
select * from books

select  top 3  A.author_name,sum(B.sold_copies) as sum1
from authors A
inner join books B
on A.book_name= B.book_name
group by A.author_name
order by sum1 desc